name: 'word_trainer'
description: A Flutter application to learn English word for a Russian user.

publish_to: 'none'

version: 1.4.0+0

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.5
  fluttertoast: ^8.2.10
  mutex: ^3.0.0
  flutter_typeahead: 5.2.0
  google_fonts: ^6.2.1
  get_it: ^8.0.3
  provider: ^6.0.1
  flutter_tts: ^4.2.1

  google_sign_in: ^7.1.0
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_crashlytics: ^4.3.9
  cloud_functions: ^5.5.2

  flutter_local_notifications: ^19.3.0
  permission_handler: ^12.0.1

  flutter_markdown_plus: ^1.0.3

  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.3

  timezone: ^0.10.0
  flutter_timezone: ^4.0.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.6

flutter:
  generate: true
  uses-material-design: true

  assets:
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
module:
  androidX: true
