name: 'word_trainer'
description: A Flutter application to learn English word for a Russian user.

publish_to: 'none'

version: 1.1.1+0

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  fluttertoast: ^8.0.8
  mutex: ^3.0.0
  intl: ^0.18.1
  # translator: 0.1.5 - replaced by embedded the source code
  flutter_typeahead: 4.6.1
  google_fonts: ^5.0.0
  get_it: ^7.2.0
  provider: ^6.0.1
  flutter_tts: ^3.2.2

  google_sign_in: ^6.1.4
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  cloud_firestore: ^4.8.0
  firebase_crashlytics: ^3.3.2

  flutter_local_notifications: ^14.1.1
  permission_handler: ^10.3.0
  path_provider: ^2.0.1
  share: ^2.0.0

  flutter_markdown: ^0.6.8

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.3

  timezone: ^0.9.2
  flutter_native_timezone: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
module:
  androidX: true
